[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minimi-para"
version = "0.1.0"
description = "A mini migration tool"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
  { name = "Petr Jindra", email = "el.mordo@gmail.com" }
]
keywords = ["migrations", "sqlalchemy", "database"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "sqlalchemy>=2.0.52,<3.0",
  "sa-values>=0.1.0,<0.2"
]

[project.optional-dependencies]
test = [
  "pytest",
]
dev = [
  "sa-values[test]",
  "build",
  "twine",
]

[project.urls]
Homepage = "https://github.com/elmordo/minimi"
Repository = "https://github.com/elmordo/minimi"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint.isort]
force-sort-within-sections = true
order-by-type = false
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
